# Generated by Django 4.2.4 on 2023-09-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_order_products_alter_order_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='creation_date',
        ),
    ]
