# Generated by Django 4.2.4 on 2023-11-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_director_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='director',
            managers=[
            ],
        ),
    ]
